# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: rustc-swift runner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: aarch64-apple-darwin, x86_64-apple-darwin

    - name: Build Rust
      run: |
        cargo build --target aarch64-apple-darwin --release

    - name: Build Xcode project
      run: |
        xcodebuild build \
          -project Proxy-Cosmodrome.xcodeproj \
          -scheme Proxy-Cosmodrome \
          -destination 'platform=macOS' \
           CODE_SIGNING_ALLOWED=NO
